# SONiC to SONiC image update on the running device.
# Command example: 
# ansible-playbook -i inventory --limit SWITCH update.yml --tags update -b -vvvvv -e CMD image_url=URL 

- fail: msg="image_url variable should be provided."
  when: image_url is not defined

- set_fact: timestamp="{{lookup('pipe','date +%Y%m%d%H%M%S')}}"

- set_fact: filename="/tmp/update_image_{{ timestamp }}"
- debug: var=filename

- name: Download SONiC image.
  local_action: get_url url={{ image_url }} dest={{ filename }}

- name: Upload SONiC image to device.
  copy:
    src: "{{ filename }}"
    dest: "{{ filename }}"

- name: Remove SONiC image from local server.
  local_action: file path={{ filename }} state=absent

- name: Update SONiC image.
  command: sonic_installer install {{ filename }} -y
  register: update_output
  ignore_errors: yes

- fail: msg="{{ update_output.stdout }}"
  when:
    - update_output.rc != 0
    - "'Running SONiC has the same version' not in update_output.stdout"

- block:
    - name: Reboot device.
      command: /sbin/shutdown -r
      async: 0
      poll: 0
      ignore_errors: true

    - name: Wait for device to come back.
      local_action: wait_for host={{ ansible_ssh_host }} state=started

  when: "'Running SONiC has the same version' not in update_output.stdout"

- block:
    - name: Wait for switch fw update to finish
      command: bash -c 'ps aux | grep "[m]lxfwmanager" ; [ $? == 1 ]'
      register: output
      until: output.rc == 0
      retries: 12
      delay: 10
      ignore_errors: true

    - name: Wait for switch initialization to finish
      pause:
        minutes: 5

    - name: Deploy minigraph file.
      copy:
        src: "minigraph/{{ dut_minigraph }}"
        dest: "/etc/sonic/minigraph.xml"

    - name: Deploy port config file.
      copy:
        src: "roles/sonicv2/files/ssw/ACS-MSN2100/port_config.ini"
        dest: "/usr/share/sonic/device/x86_64-mlnx_msn2100-r0/ACS-MSN2100/port_config.ini"
      when: sonic_hwsku == 'ACS-MSN2100'

    - name: Workaround. Deploy port config file for ACS-MSN2700 platform.
      shell: sed -i -r -e '1s/\S+//4' -e '2,$s/\S+//3' /usr/share/sonic/device/x86_64-mlnx_msn2700-r0/ACS-MSN2700/port_config.ini
      become: yes
      when: sonic_hwsku == 'ACS-MSN2700'

    - name: Reload minigraph.
      shell: config load_minigraph -y

    - name: Save config.
      shell: config save -y

#    - name: Restore firsttime
#      shell: 'touch /host/image-$(cat /etc/sonic/sonic_version.yml | grep build_version | cut -f2 -d" ")/platform/firsttime'

#    - name: Reboot device.
#      command: /sbin/shutdown -r
#      async: 0
#      poll: 0
#      ignore_errors: true

#    - name: Wait for device to come back.
#      local_action: wait_for host={{ ansible_ssh_host }} state=started

  when: dut_minigraph is defined

- name: Gathering minigraph facts about the device
  minigraph_facts: host={{ inventory_hostname }}
#  connection: local
  become: no
  tags: always

- name: Verify interfaces are up correctly
  wait_for:
      path: /sys/class/net/{{ item }}/operstate
      search_regex: up
  with_items: "{{ minigraph_ports }}"
#  when: (sonic_hwsku == 'ACS-MSN2700' and item != 'Ethernet124') or (sonic_hwsku == 'ACS-MSN2100' and item != 'Ethernet36')

- name: Workaround. Wait for LAG interfaces.
  pause:
    minutes: 5
  when: topo == "t0" or topo == "t1-lag"

- name: Verify PortChannel interfaces are up correctly
  wait_for:
      path: /sys/class/net/{{ item }}/operstate
      search_regex: up
  with_items: "{{ minigraph_portchannels.keys() }}"

- name: Verify VLAN interfaces are up correctly
  wait_for:
      path: /sys/class/net/{{ item }}/operstate
      search_regex: up
  with_items: "{{ minigraph_vlans.keys() }}"
